### ISSUE TITLE
Results, react-css or reactcss?

### ISSUE THREAD

**Issue by baldwmic** [A-gambit/CSS-IN-JS-Benchmarks#16]
In the [results](https://github.com/A-gambit/CSS-IN-JS-Benchmarks/blob/76148b08aa3fafbef8df2fac6a3bf99891e120c3/RESULT.md), `react-css` link goes to https://github.com/facebook/react.

Is that correct, or is it supposed to go to https://github.com/casesandberg/reactcss ? I'm confused about what `react-css` means in this case?

**Comment by A-gambit** [comment]
Hey,
`react-css` is simply `react` with CSS styles and inline-styles for a background of table squares.

**Comment by baldwmic** [comment]
Thanks for the clarification @A-gambit 😄

**Comment by bloodyowl** [comment]
@A-gambit maybe renaming it `react (with plain CSS)` would help disambiguate? I can put up a PR if you like
