### ISSUE TITLE
Add emotion

### ISSUE THREAD

**Issue by mxstbr** [A-gambit/CSS-IN-JS-Benchmarks#17]
I remember that @tkh44 added emotion to this benchmark, but I can't seem to find it in this repo. Any ideas where that went?

**Comment by A-gambit** [comment]
Hey, Max. @tkh44 have said me that he would add it to the benchmarks. But unfortunately, he hasn't done that. So, I will add it on this week.

**Comment by tkh44** [comment]
Added in #18
