### ISSUE TITLE
React Native

### ISSUE THREAD

**Issue by brunolemos** [A-gambit/CSS-IN-JS-Benchmarks#25]
Is there a version of this repo for react native or a way to support it here?

**Comment by A-gambit** [comment]
I like this idea :) I will create it on this weekends if I have a free time.

**Comment by brunolemos** [comment]
Created here: [brunolemos/react-native-css-in-js-benchmarks](https://github.com/brunolemos/react-native-css-in-js-benchmarks) 😀
