### ISSUE TITLE
Use a proper benchmarking tool

### ISSUE THREAD

**Issue by kof** [A-gambit/CSS-IN-JS-Benchmarks#6]
Unless you use something like bench.js, those results vary so much that they are almost useless.

Have you seen https://github.com/PepijnSenders/css-in-js-perf-tests ?

They use proper benchmark, though the way the tests are written is suboptimal, because not the full render cycle happens. Maybe you should team up with that project and use their test running infrastructure but add your rendering in a real browser through karma.

**Comment by A-gambit** [comment]
Just do it :)

**Comment by jedwards1211** [comment]
@A-gambit what does your answer even mean?
